### ISSUE TITLE
Shop Issue

### ISSUE THREAD

**Issue by CqldFire** [mrrhetorical/COM-Warfare#1]
Hello, I have an issue with the shop. I have 65 different guns, and when I go into the gun part of the shop and try to click on a gun to purchase it, nothing happens. I am using the 2.13.0 beta version of the plugin on a 1.12.2 spigot server. Here is my guns.yml: https://pastebin.com/0YvjwCmT

**Comment by mrrhetorical** [comment]
Are there any errors in the console when you're attempting to buy a gun?

**Comment by CqldFire** [comment]
No there is not.

**Comment by mrrhetorical** [comment]
This issue has been fixed in version 2.13.4.223
